---
- name: Create docker network {{ name }} if not present
  shell: |
    if [[ -z {{ get_existing_docker_network }} ]]; then \
      docker network create {{ is_attachable | ternary('--attachable', '') }} --driver {{ driver }} {{ name }}; \
    fi
  when: remove == False

- name: Remove docker network {{ name }} if present
  shell: |
    if [[ "{{ get_existing_docker_network }}" ]]; then \
      docker network rm {{ name }}; \
    fi
  when: remove
